runtime: nodejs14
# Environment-variables:
env_variables:
  PORT: 8080
  DB_USER: postgres
  DB_PASS: Fz3Z7ma32YXEzkH9rEhBN7kg
  DB_NAME: postgres
  DB_STAGE: development
  CLOUD_SQL_CONNECTION_NAME: glossy-mason-313319:europe-west3:waterme01
