runtime: python27
api_version: 1
threadsafe: yes


handlers:

  - url: /(.+\.js)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.css)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.css)
    secure: always
    redirect_http_response_code: 301

  - url: /(.*\.woff)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.*\.woff)
    mime_type: application/font-woff
    redirect_http_response_code: 301

  - url: /(.*\.woff2)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.*\.woff2)
    mime_type: application/font-woff2
    redirect_http_response_code: 301

  - url: /(.+\.png)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.jpg)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.jpg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.gif)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.gif)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.svg)
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/waterMe/\1
    upload: dist/waterMe/favicon.ico
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.json)
    static_files: dist/waterMe/\1
    upload: dist/waterMe/(.+\.json)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+)
    static_files: dist/waterMe/index.html
    upload: dist/waterMe/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_files: dist/waterMe/index.html
    upload: dist/waterMe/index.html
    secure: always
    redirect_http_response_code: 301

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
